// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlnhpqkgyigztumogcge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sbmhwcWtneWlnenR1bW9nY2dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTQ1NzAsImV4cCI6MjA2NjE3MDU3MH0.RAcSjvDPO4c3R_SyZp1dvFaneDlQJr2PBw_EO5eXa5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);